### PR TITLE
Add lint-allow for empty loop

### PR DESCRIPTION
**Pull request by Ben-PH**

### CODE REVIEW

**Comment by SergioGasquez** [comment]
Hi! Thanks for the contribution! Do you mind elaborating what is the purpose of adding this?

**Comment by SergioGasquez** [comment]
Not sure if your issue, #95 is related with this, but you can change the CI command: `cargo clippy -- -D warnings  -A clippy::empty_loop` and it will allow the empty loop.

**Comment by MabezDev** [comment]
> Not sure if your issue, https://github.com/esp-rs/esp-template/issues/95 is related with this, but you can change the CI command: cargo clippy -- -D warnings  -A clippy::empty_loop and it will allow the empty loop.

I think this PR is more intended for the generated project, if you run clippy once generated it will produce an error without this lint.

**Comment by SergioGasquez** [comment]
> I think this PR is more intended for the generated project, if you run clippy once generated it will produce an error without this lint.

Yes, but, is that something that we want to avoid?

**Comment by Ben-PH** [comment]
I discovered the lint when running the CI I included in the issue mentioned.

I'm not a fan of adding the allow of empty loop at the clippy invocation level. Using an annotation it signals that busy loops are  undesired inclusion in the codebase, with that specific loop being a carefully considered exception. Allowing at the clippy-invocation level signals that busy-loops are a generally accepted inclusion, which is not the case.

**Comment by bjoernQ** [comment]
Probably it's a good thing to get a warning about this since usually users should add code to make it a non-empty loop. 🤔
Maybe we should add a comment instead telling users to add their code there and link to the esp-hal examples and/or the esp-book?

**Comment by Ben-PH** [comment]
I think any approach that shows that the default clippy lints are taken into account within the code-base with respect to that specific empty loop is suitable.

How about instead of a busy-loop, it stops the process indefinitely, followed by an `unreachable!("some-useful-comment");`, or perhaps:

```rust
loop {
    println!("TODO: set led-pin high for a blinky");
    delay.delay_ms(500);
    println!("TODO: set led-pin low for a blinky");
    delay.delay_ms(500);
}
```

That way, the templated sets things up for the monitored hello-world, and leads the user into the next step of exploring the platform. This resolves the need for considering clippy entirely, and provides the documentation you refer to. Maybe add a comment to an example that will get you started towards a blinky?

**Comment by SergioGasquez** [comment]
Another option would be to only add a `delay` into the loop, this way the template is still "minimal" and clippy won't complain

**Comment by Ben-PH** [comment]
Seems like we are converging on a solution.

How about I update the PR to allow for this code-snippet, then you can edit the PR if there are any final details (interval, naming, message, etc). I'll ping you when it's ready.

```rust
loop {
    println!("tick...");
    delay.delay_ms(1_000);
}
```

Might be cool to show some of the nice rust ergonomics. I imagine a large portion of people using this template don't have much of a rust background (C/C++ embedded, or higher-level, and want to explore embedded, and gravitate towards rust). I put this together with that thought in mind:

```rust
println!("Hello, world!");

print!("Entering deep-sleep in ";
for i in 1..=3.reverse() {
    println!("{}...", i);
    delay.delay_ms(1_000);
}
println!("Good Night!");
let never_type: ! = // Enter deep sleep here
unreachable!();
```

**Comment by SergioGasquez** [comment]
Between the two proposed options, I'd go with the first one adding only one `println!` and a delay in the loop.

The template should not showcase anything in special in my opinion, it should give you a nice and simple starting point for a project. Showcases and walkthroughs should be done in the [training book](https://github.com/esp-rs/no_std-training)/repository examples.

**Comment by SergioGasquez** [comment]
Since #108 just got merged, we can close this PR.

**Pull request closed without merging**
