### PR TITLE
Added release and dev profiles, matching those in the esp-idf-templat…

### PR DESCRIPTION
**Pull request by drdozer**
This pull request adds profile sections to Cargo.toml for release and dev. It matches the esp-idf-template settings.

### CODE REVIEW

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks for your contribution!

**Comment by jessebraham** [comment]
Out of curiosity, what's the rationale behind these particular settings? The `dev` profile already sets `debug = true` by default for example, so that's redundant.

**Comment by drdozer** [comment]
I copied the "debug=true" text as- is from the other template. So that's
why it is in this pr :)

**Comment by MabezDev** [comment]
I'm not super convinced about changing the opt-levels, they are changed on esp-idf-template because in general the esp-idf crates and std consume more code space. Not so much of an issue of bare metal.

I do like the change to add debug = true for the release profile though.

**Comment by drdozer** [comment]
Does setting the opt-level potentially hurt?

**Comment by MabezDev** [comment]
Generally, you don't optimize for size until you need to. In doing so you often miss out on better optimizations that the default release opt level may yield.

**Pull request closed without merging**
