### PR TITLE
Toolchain update, fix `cargo-generate`, and fix scripts

### PR DESCRIPTION
**Pull request by SergioGasquez**
- Updated toolchain version to `1.62.1.0`
- Added an extra step that installs cargo-generate via cargo if the binary installation failed
- Formated scripts
- Fixed an issue where elf path in scripts was not correct for projects with `-` on the name
- Update https://github.com/esp-rs/esp-hal/pull/134 changes
- Update `xtensa-atomic-emulation-trap` version

### CODE REVIEW

**Comment by SergioGasquez** [comment]
Checks are failing since `cargo-generate` released a new version yesterday and CI for generating binary assets failed, see: https://github.com/cargo-generate/cargo-generate/issues/708

**Comment by jessebraham** [comment]
Are we going to have to do this every time there's a new release? Are we able to automatically use the latest version in any way?

**Comment by SergioGasquez** [comment]
> Are we going to have to do this every time there's a new release? Are we able to automatically use the latest version in any way?

At the moment, yes. See: https://github.com/esp-rs/rust-build/issues/125#issuecomment-1192516426

**Comment by jessebraham** [comment]
Is there a reason we can't use `https://github.com/esp-rs/rust-build/releases/latest` instead of specifying the version? I don't know if this will ignore pre-releases or not, I guess that would be my only concern.

**Comment by SergioGasquez** [comment]
> Is there a reason we can't use `https://github.com/esp-rs/rust-build/releases/latest` instead of specifying the version? I don't know if this will ignore pre-releases or not, I guess that would be my only concern.

We could use `latest`, but that would be more "unstable", I've added the issue to [today's community meeting](https://github.com/esp-rs/rust/discussions/130#discussioncomment-3229078) to discuss it

**Comment by SergioGasquez** [comment]
I've added an extra step that installs `cargo-generate` via cargo if the binary installation failed since we don't know when `cargo-generate` binaries will be uploaded and we already had other issues with cargo-generate installation so having 2 sources can be useful in reducing third parties errors

**Review by jessebraham — APPROVED** [review]

**Pull request merged**
