### PR TITLE
Add a default prompt

### LINKED ISSUE #79: Add default prompt
Similar to https://github.com/esp-rs/esp-idf-template/issues/95, we could add a prompt that remove complex questions (like the alloc, devcontainer, wokwi prompts)

### PR DESCRIPTION
**Pull request by SergioGasquez**

### CODE REVIEW

**Comment by bjoernQ** [comment]
Seems like CI unhappy about the allocator on nightly

**Comment by jessebraham** [comment]
There's been a new patch release for `esp-alloc`, though I'm not sure it will make any difference. Just FYI, though.

**Comment by SergioGasquez** [comment]
> Seems like CI unhappy about the allocator on nightly

Yes, using recent nighties fails.


> There's been a new patch release for esp-alloc, though I'm not sure it will make any difference. Just FYI, though.

The issue still persists in `esp-alloc v0.2.1`

**Review by bjoernQ — APPROVED** [review]
LGTM

**Review by jessebraham — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
