### PR TITLE
Improve dev container support

### PR DESCRIPTION
**Pull request by SergioGasquez**
- Add devcontainer support for:
  - VS Code Dev Containers
  - Gitpod
  - GitHub Codespaces
- When using dev containers:
  - Wokwi support
  - Web flasher support
  - Readme with instructions

### CODE REVIEW

**Review by MabezDev — APPROVED** [review]
This is awesome! LGTM!

I did have a question about the two new shell scripts, are they needed for use in Rust projects like this one? Seems like the only thing that needs to be set is `WOKWI_HOST`, then it's possible to use web-flash or wokwi-server as a cargo runner? Just a thought! By no means something to stop this being merged :).

**Comment by SergioGasquez** [comment]
Thanks for the quick review! The main purpose of the scripts is to make VS tasks less complex and, when using Wokwi in Gitpod/GH Codespaces, remove the need to export `WOKWI_HOST` from the user.

That being said, we could maybe move the complexity away from the scripts into wokwi-server and `task.json` and get rid of the 3 bash files

**Comment by jessebraham** [comment]
Thank you for this Sergio, great work!

I would personally like to see the scripts either moved into a `scripts` directory or (preferably) removed altogether if possible. Again though, this is not a blocking issue and I'm more than happy to merge this as-is. I completely understand if you've moved on to other things and don't want to poke at this anymore right now, so please just let me know your plan and I will act accordinly.

**Comment by SergioGasquez** [comment]
I moved the scripts into a `scripts` folder for the moment and in the future, I will be trying to get rid of them by moving part of the logic to `wokwi-server`

**Review by jessebraham — APPROVED** [review]
Thanks for making those changes!

**Pull request merged**
