### PR TITLE
Add ESP32-C2 support

### PR DESCRIPTION
**Pull request by rfael**
Hello, I've added support for ESP32-C2, please take a look at it and let me know what do you think.

Related issue: #34

### CODE REVIEW

**Comment by rfael** [comment]
@MabezDev Could you trigger pipeline gain?

**Comment by rfael** [comment]
Docker check is failing for ESP32-C2. It looks like script `install-rust-toolchain.sh` from https://github.com/esp-rs/rust-build repository does not support this MCU. 
I think repo rust-build have to be updated before this PR is is merged. Do you agree?

**Comment by SergioGasquez** [comment]
Hi! Thanks for your contribution, at the moment we are evaluating a big update on the template, see https://github.com/esp-rs/esp-template/issues/45. Currently, I've done some work to migrate the Dockerfile from the `rust-build` script (which is feature frozen) to `espup`, see https://github.com/esp-rs/esp-template/compare/main...SergioGasquez:esp-template:feature/architectore-refactor. This changes also include `esp32c2` support but we might go for the approach suggested in #55 as it simplifies things and keeps the template in a single folder. 

Adding esp32c2 to rust-build is probably something we would need to handle too, as even if its feature frozen I guess we need to support all our chips.

**Comment by rfael** [comment]
@SergioGasquez Thanks for clarification!

**Comment by jessebraham** [comment]
Thanks for the PR, but this was also added in #55.

**Pull request closed without merging**
