### PR TITLE
Use unified esp-hal

### LINKED ISSUE #148: Use new `esp-hal` package instead of chip-specific HAL packages once published

### PR DESCRIPTION
**Pull request by SergioGasquez**
- Use unified esp-hal
- Update esp-wifi

### CODE REVIEW

**Comment by jessebraham** [comment]
New release is out!

**Comment by SergioGasquez** [comment]
Updated it to use the released `esp-hal`, once we have an `esp-wifi` release, I'll finish this PR.

**Comment by MabezDev** [comment]
esp-wifi 0.4 is now released!

**Comment by SergioGasquez** [comment]
Should be now ready for review/merge!

**Review by MabezDev — APPROVED** [review]
LGTM, thanks!

**Review by bjoernQ — APPROVED** [review]
LGTM

**Pull request merged**
